Revert org.apache.felix.metatype-1.0.2
Version 1.0.4 exports org.osgi.util.tracker which causes
java.lang.SecurityException: class "org.osgi.util.tracker.BundleTrackerCustomizer"'s signer information does not match
signer information of other classes in the same package

with equinox